# Generated by Django 4.2.2 on 2023-06-27 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_decouvrir'),
    ]

    operations = [
        migrations.CreateModel(
            name='offrefield',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('ImageDoffre', models.ImageField(upload_to='images/')),
                ('reduction', models.DecimalField(decimal_places=2, default=0, max_digits=5, null=True)),
            ],
        ),
    ]
