# Generated by Django 4.2.2 on 2023-07-01 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_alter_image_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offrefield',
            name='reduction',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
