# Generated by Django 4.2.2 on 2023-07-03 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_alter_offrefield_reduction'),
    ]

    operations = [
        migrations.CreateModel(
            name='bangalo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ImageBangalo', models.ImageField(upload_to='images/')),
                ('PlaceRestante', models.IntegerField(default=0, null=True)),
            ],
        ),
    ]
